# Generated by Django 4.2.7 on 2023-12-09 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bankingapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deposit',
            old_name='deposit_amount',
            new_name='amount',
        ),
    ]
