# Generated by Django 4.2.6 on 2023-12-12 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankingapp', '0003_rename_amount_deposit_deposit_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('principal_amount', models.FloatField()),
                ('annual_interest_rate', models.FloatField()),
                ('compounding_frequency', models.IntegerField()),
                ('time_period_years', models.FloatField()),
            ],
        ),
    ]
